### PR TITLE
fix: Make Fastify platform work

### PR DESCRIPTION
**Pull request by yusufkandemir**
Discovered thanks to #78

See
https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-fastify#example
https://www.fastify.io/docs/latest/Reference/Routes/#async-await

### CODE REVIEW

**Comment by smolinari** [comment]
@yusufkandemir - Hey Yusuf. Fancy meeting you here! :grin: 

Is this why, when I tried to migrate (my Fastify/ NestJS app) to Yoga last week, I wasn't getting anything back from the API? Shouldn't there be some sort of test for this? :smiley:  

Scott

**Comment by yusufkandemir** [comment]
Hey Scott, same 😁 

I was experiencing the same behavior, so most probably yes. I tried this fix and it worked fine. Related documentation and examples make sense, so it seems it's the correct fix to apply here.

There are some tests in place, I even tried adding a GraphiQL-specific test, but interestingly, they passed with and without the fix. I tried upgrading Fastify in this repo to v4, but it didn't make a difference. So, the race condition might become obvious only in real environments such as in a browser where there is extra overhead.

**Comment by smolinari** [comment]
Welp. If this gets merged, I'll try again to migrate. 

Scott

**Comment by smolinari** [comment]
@charlypoly - Any chance to get this merged and released soon?

Scott

**Comment by enisdenjo** [comment]
Hey there, thanks for PR-ing this! Can you please fix the linting issues? I'll merge then ASAP.

**Review by enisdenjo — APPROVED** [review]
Linting issue comes from master... Will fix myself.

**Comment by Urigo** [comment]
thank you @yusufkandemir !
We would love to thank you publicly, if you can share your Twitter/LinkedIn profile (also in private if you prefer) ?

**Comment by smolinari** [comment]
Btw, this fixed my problem. I can now run Yoga instead of Mercurius with NestJS and Fastify. Awesome! Thanks everyone! :+1: :100: :tada: 

Scott

**Comment by yusufkandemir** [comment]
@Urigo you are welcome, and thanks! https://www.linkedin.com/in/yusuf-kandemir/

**Comment by Urigo** [comment]
https://www.linkedin.com/posts/activity-7034515817975164929-p70k?utm_source=post_nba&utm_medium=member_desktop&utm_campaign=copy

**Pull request merged**
